#
#   Remove the wine prefixes created by our wrapper from user 
#   home directories. This does not delete save files, which 
#   are kept in ~/Gamesaves/anomaly
#

# See wrapper script
WINEPREFIXES="/home/*/.wine/stalker-anomaly"

post_remove() {
  
  echo " -> Cleaning user directories"

  shopt -s nullglob   # Allow null globs
  for d in "${WINEPREFIXES}"; do 
    echo "     -> $d"; 
    rm -rf "$d"
  done
  
}
